export const ALLGALLERIES_SET_GALLERIES = 'GALLERYS:SET_GALLERYS';
export const SINGLEGALLERY_SET_PHOTOS = 'SINGLEGALLERY:SET_GALLERY';
export const GLOBAL_SET_USERNAME = 'GLOBAL:SET_USERNAME';
export const GLOBAL_SET_IMAGESIZE = 'GLOBAL:SET_IMAGESIZE';